### PR TITLE
571 optimize search ranking

### PR DESCRIPTION
**Pull request by philboeselager**
Issues: #571, #461, #455 .
New functionality:

- Improve search ranking --> boost fields during search.
- Add test for search ranking (ElasticsearchRepositoryTest.testSearchRankingNameHitsFirst()): check field "name" has highest weight.
- Make boosting configurable in conf/search.conf : boost name and also alternateName .
- Setup new Java class SearchConfig serving search.conf in the code.
- Embed result of SearchConfig.getBoostsForElasticsearch() as a member field in QueryContext.
- In search ranking test, inject boosting in query via QueryContext.

Optional TODO: if boosting results are not satisfying "as are", improve them via conf/search.conf .

### CODE REVIEW

**Comment by literarymachine** [comment]
Deployed to beta, I would expect hbz to be ranked first here: https://beta.oerworldmap.org/resource/?q=hbz

**Comment by literarymachine** [comment]
Also, if I recall our discussion in Cologne correctly, we are not using a general `integration` branch any more. But I might be wrong here, we didn't really explicitly state that in the [conclusion of the minutes](http://etherpad.lobid.org/p/github-workshop)! I would say we start following the [lobid dev process](http://hbz.github.io/#dev-process) but potentially use story branches to integrate smaller tasks. Ok with you and @j0hj0h?

**Comment by trugwaldsaenger** [comment]
I checked it with "BC Campus":

1. The first entry of the organization "BC Campus" ranks first:
https://beta.oerworldmap.org/resource/?q=BC%20Campus&from=0&size=25
2. The second entry of the organization "BC Campus" (duplicate!) ranks 270
https://beta.oerworldmap.org/resource/urn:uuid:374cce8a-2fbc-11e5-a656-001999ac7927
3. The BC Campus Open Textbook Project (which is linked to the organization ranked 1) ranks 271
4. The BC Campus OpenEd Service, which is available on production, seem not to be included in beta. On production it ranks first.

I think it would be important that dublicates should be ranked close to each other in order to find and delete them. Services and projects connected to an entry should be ranked with priority as well. Furthermore I do not understand why we get 278 results when searching for "BC Campus".

**Comment by literarymachine** [comment]
@philboeselager Due to our index structure (using `WebPage` as a wrapper), the fields to boost have to be prefixed by `about`. (hbz)[https://beta.oerworldmap.org/resource/?q=hbz] ranks properly now!

**Comment by literarymachine** [comment]
> The second entry of the organization "BC Campus" (duplicate!) ranks 270

This is because the name is spelled "BCcampus" there (lacking the space), which results in a completely separate tokenization. Especially in cases where abbreviations such as "BC" are involved, this is hard to fix automatically. Duplicates with equal names should be ranked together now.

> The BC Campus Open Textbook Project (which is linked to the organization ranked 1) ranks 271

We are currently boosting mainly `name` and `alternateName`, as requested in #455 and #461.

> The BC Campus OpenEd Service, which is available on production, seem not to be included in beta.

Right, the indexes have not been synced in a while. Things added to production are not automatically added to beta, they are completely separate indexes so that beta can be used for testing at will.

> Services and projects connected to an entry should be ranked with priority as well.

See below for an initial list of fields, ordered by priority.

> Furthermore I do not understand why we get 278 results when searching for "BC Campus".

This has to do with our current index configuration. Entries that are linked together are indexed together; because BC Campus is a member of OEC, its name is indexed along with the other members. Because we are currently searching accross all fields by default, all of those other members show up in the result. I agree that this is counter intuitive if not to say plain wrong. a386affd8b5f8db8ad04e39d1b48a3f709546729 has added the possibility to explicitly configure which fields to search, so we can start to collect them here, perhaps in descending order:

- name
- alternateName
- provider.name
- provider.alternateName
- agent.name (="Project lead")
- agent. alternateName
- participant.name
- participant.alternateName

**Comment by literarymachine** [comment]
Check out the search for [BC Campus](https://beta.oerworldmap.org/resource/?q=BC%20Campus&from=0&size=25) now. I fixed the name of the duplicate so that they both rank first, the connected project ranks next. Finally, "Almae Matris Studiorum Campus" is also found because it contains "Campus". I would consider this plausible.

**Comment by philboeselager** [comment]
> Because we are currently searching accross all fields by default, all of those other members show up in the result. I agree that this is counter intuitive if not to say plain wrong.

+1
Let's remove "_all" from the search fields list.

> a386aff has added the possibility to explicitly configure which fields to search, so we can start to collect them here, perhaps in descending order:
    name
    alternateName
    provider.name
    provider.alternateName
    agent.name (="Project lead")
    agent. alternateName
    participant.name
    participant.alternateName

Looks good. We should in any way keep "What you get is what you see." in mind. That means, every hit must be directly comprehensible. I would start with that list & the following boosts maybe and expand it on demand, i. e. if we detect, something is missing in the search results.

- name : 9
- alternateName : 6
- provider.name : 5
- provider.alternateName : 4
- agent.name (="Project lead") : 4
- agent. alternateName : 3
- participant.name : 2
- participant.alternateName : 1

(Please register: we can also set floating numbers here, if we need finer adjustments.)

> Finally, "Almae Matris Studiorum Campus" is also found because it contains "Campus". I would consider this plausible.

+1

> I would say we start following the lobid dev process but potentially use story branches to integrate smaller tasks. Ok with you and @j0hj0h?

+1.
I will merge request from story into master then.

**Comment by acka47** [comment]
I went through the test cases from this PR and some more and can say that you arrived at a good and intuitive solution. +1

**Comment by literarymachine** [comment]
https://github.com/hbz/oerworldmap/commit/d86a73018d95f6bde3d2d966af1d1d6e680d4889

**Pull request closed without merging**
