### PR TITLE
Add memberOf to Service in JSON schema.

### LINKED ISSUE #467: JSON Schema: Add memberOf to Service template
As what we classify as services can be members of the OEC (for example http://www.oeconsortium.org/members/view/237/), we need the possibility to say so in our data. This currently is not possible, see https://oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927.

### PR DESCRIPTION
**Pull request by acka47**
Fixes #467.

### CODE REVIEW

**Comment by literarymachine** [comment]
As discussed in https://github.com/hbz/oerworldmap/pull/457#issuecomment-158109645, please update the test JSON files.

**Comment by acka47** [comment]
> As discussed in https://github.com/hbz/oerworldmap/pull/457#issuecomment-158109645, please update the test JSON files.

As far as I can see, you already did this regarding the `tag` field. If you mean I should add other missing fields, I made a separate issue for this at #480.

**Comment by literarymachine** [comment]
> As far as I can see, you already did this regarding the tag field.

Did this for `tag` in https://github.com/hbz/oerworldmap/commit/3d3a871746acfdd581053532766b4abf0ea4c422. In this PR, I added test cases for `memberOf` (and `member`) field myself so that I could merge in order to work on #467.

**Comment by acka47** [comment]
Ah, now I understand. Just insist in me doing this if I also forget next time so that hopefully I get it into my workflow at some point...

**Pull request merged**
