### PR TITLE
652 escape special chars simple query string builder

### PR DESCRIPTION
**Pull request by philboeselager**
Use SimpleQueryStringBuilder instead of QueryStringQueryBuilder. This escapes special characters. As a consequence, asterisk search does no longer work.

### CODE REVIEW

**Comment by literarymachine** [comment]
Could you add a test case to verify that `_missing_` queries are not broken again (#785)?

**Comment by literarymachine** [comment]
@philboeselager 2a1fbb9 is not an appropriate test case. Not the controller should be tested, but ElasticsearchRepository, and not only the 200 result code is relevant but the actual hit count.

**Comment by philboeselager** [comment]
@literarymachine You mean: better test that in BaseRepositoryTest ?

**Comment by literarymachine** [comment]
> @literarymachine You mean: better test that in BaseRepositoryTest ?

Sorry, is there a `_missing_` test in BaseRepositoryTest? Can't find it.

**Comment by philboeselager** [comment]
Replaced by https://github.com/hbz/oerworldmap/pull/824.

**Pull request closed without merging**
