### PR TITLE
German translation of UI

### LINKED ISSUE #761: Enable internationalization and localization of website by third parties
We received a request by someone who wants to translate the site into his native language:

> I am writing this letter to let you know that as a Country Champion I would like to Translate OER World Map web site pages into my native language Bengali

I guess all the stuff that needs to be translated is in these three places:
- [static pages](https://github.com/hbz/oerworldmap/tree/master/public/pages) about, faq, contribute, imprint
- labels.properties
- description.properties

Did I miss something? Anyway, how should people translate this? Just by providing the same files in their language? 

We probably should start looking at localization and internationalization platforms. There are lots of them. Here are ~~two~~  three that are open source and look promising:
- [Serge](https://serge.io/) by Evernote
- Zanata: http://zanata.org/
- http://pootle.translatehouse.org/

### LINKED ISSUE #957: Translate UI to German

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #761, fixes #957

### CODE REVIEW

**Comment by acka47** [comment]
Looks good. I have looked at most of the non-static pages. The only thing that isn't translated yet is "Contribute" and "About" in the top navigation bar.

**Comment by literarymachine** [comment]
> The only thing that isn't translated yet is "Contribute" and "About" in the top navigation bar.

As mentioned in the [README](https://github.com/hbz/oerworldmap/tree/761-translation#localizations), those link titles are drawn from the front matter of the static pages. Even if you don't want to translate the whole pages yet, you can simply make a copy as described and only change the title. What is also not translated yet, is [conf/descriptions_de.properties](conf/descriptions_de.properties).

**Comment by karindr** [comment]
I am ready and will continue to translate in crowdin as discussed with @acka47.

**Comment by literarymachine** [comment]
So I can merge and deploy this, right?

**Comment by acka47** [comment]
Yes, please.

**Comment by literarymachine** [comment]
In `labels_de` the term "Country champion" is also used in German. In `ui_de`, the term "Länderpate" is used. Is this correct for now?

**Comment by literarymachine** [comment]
Superseded by #1287.

**Pull request closed without merging**
