### PR TITLE
User login

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by trugwaldsaenger** [comment]
The main process works for me. But we still have to refine some details:
1) The mail comes from a gmail address (might be different later on production). It was delivered in my junkmail folder. Before I could input the token, the login-process was canceled and I had to do the whole process again, asking for another token. We should see if other team members make the same experience.
2) After login, the user should automatically should land on the resource page with the buttons to input data:
https://beta.oerworldmap.org/resource/. 
We should also change the homepage and the contribute page, to make the navigation clear. I will create different issues for this.

**Comment by literarymachine** [comment]
> 1) The mail comes from a gmail address (might be different later on production). It was delivered in my junkmail folder. Before I could input the token, the login-process was canceled and I had to do the whole process again, asking for another token. We should see if other team members make the same experience.

Didn't feel like configuring the hbz-server on a Sunday night, obviously this is a preliminary setup. The login-process does not cancel itself - you must have cancelled the popup?

> 2) After login, the user should automatically should land on the resource page with the buttons to input data:

I do not agree. Currently, the user simply stays on the page she logged in from, which is what I would expect. Not to say we couldn't change it, though.

**Comment by trugwaldsaenger** [comment]
This issue is related to #485

**Comment by literarymachine** [comment]
Merging to integration first.

**Pull request closed without merging**
