### PR TITLE
Adjust contactPoint to indicate contact person.

### PR DESCRIPTION
**Pull request by acka47**
See #368.

### CODE REVIEW

**Comment by acka47** [comment]
The property was already in the schema (with an array of strings). We already had one usage of contactPoint in the data indicating an email list. I removed this and will adjust the two or three entries with organization & contact person as soon as this is merged and deployed.

**Comment by literarymachine** [comment]
> We already had one usage of contactPoint in the data indicating an email list. I removed this

The old usage of `contactPoint` still occurs in https://oerworldmap.org/resource/urn:uuid:f3662ed2-15d0-11e5-a98c-dfd0cff00d2f

**Comment by acka47** [comment]
> The old usage of `contactPoint` still occurs in https://oerworldmap.org/resource/urn:uuid:f3662ed2-15d0-11e5-a98c-dfd0cff00d2f

I fixed this. I guess, we can merge it, then.

**Comment by literarymachine** [comment]
Nope. This will unfortunately require an update of the Elasticsearch mapping, even if no instance data is present any more.

**Pull request merged**
