### PR TITLE
Add definition for policy reference number field

### PR DESCRIPTION
**Pull request by literarymachine**
See #1938

### CODE REVIEW

**Review by gandalfar — APPROVED** [review]

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by dr0i** [comment]
Selfassigned since there are problems, see https://github.com/hbz/oerworldmap-ui/pull/634#issuecomment-692872398.

**Comment by dr0i** [comment]
After proper deployment, please have a look again @gandalfar.

**Comment by gandalfar** [comment]
This is now working correctly on beta. Please deploy to production @dr0i .

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
