### PR TITLE
Add sort parameter

### LINKED ISSUE #292: Sort stories reversed chronological
The stories should be sorted in an reversed chronological order, so that the newest stories are displayed on the top of the list.

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes #292

### CODE REVIEW

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by literarymachine** [comment]
ping @trugwaldsaenger

**Comment by trugwaldsaenger** [comment]
Mmmh - the stories seem to be sorted according to the "contributed by" date now. The problem is that this date is different from the date of publication. The date of contribution refers to the time, when a story "enters" the editorial board. The date of publlishing refers to the time, when the story has been put to the production server. Accoding to my understanding it would make more sense to order the stories according to the date of publishing than to the date of contribution.

**Comment by literarymachine** [comment]
Ok, that was not clear to me. Now sorted by date of publication, see https://beta.oerworldmap.org/

**Pull request merged**
