### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by drrobertfarrow**

### CODE REVIEW

**Comment by literarymachine** [comment]
@drrobertfarrow: `landingpage_call_to_register` is currently set to *"Register for an account to"* - this seems to be incomplete?

**Comment by drrobertfarrow** [comment]
I think that needs to be deleted...

**Comment by literarymachine** [comment]
Meaning that there simply is no text above email-address input and country selection?

**Comment by drrobertfarrow** [comment]
How about "Register for an account to join the OER World Map initiative"?

**Comment by literarymachine** [comment]
Hmm. We don't really have accounts yet, like @j0hj0h said this morning. It initially said something along the lines of "Leave your email address to be kept up to date".

**Comment by drrobertfarrow** [comment]
How about 'Share your email address to be kept up to date with OER World Map".  I think 'share' is probably more in the spirit of things anyway

**Comment by literarymachine** [comment]
Sorry if I'm splitting hairs here, but I think that this particular wording is very important. We do not want to discourage people. To me, "sharing" sounds like email addresses would in some way be publicized. Also I think I would favor something more "active". How about: `Leave your email address and we will keep you posted`?

**Comment by buschfeld** [comment]
I agree to Felix that "sharing" sounds like my mail-account is risking a bunch of spam-mails. But I do not think that his suggestion "keep you posted" is correct English, but my proposal (which also has to be reviewed by a native speaker) would be quite similar: "Be part of the movement: Leave your email and we will keep you informed!"

**Comment by literarymachine** [comment]
> But I do not think that his suggestion "keep you posted" is correct English

http://de.pons.com/%C3%BCbersetzung/englisch-deutsch/keep+you+posted

**Comment by drrobertfarrow** [comment]
I think 'keep you posted' is fine in English.  It is quite informal but there's nothing wrong with that!  We want to be friendly and encourage sharing, but not come across in any way as spammers.  How about:

"Share your email and we'll keep you posted! (Don't worry, we won't pass it on to anyone else)"

**Comment by literarymachine** [comment]
> "Share your email and we'll keep you posted! (Don't worry, we won't pass it on to anyone else)"

I like that. We had a great little workshop yesterday on data privacy. There will be some more incoming textual changes, so I'm postponing merging until those changes have also been incorporated.

**Pull request merged**
