### PR TITLE
Story/#9

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by literarymachine** [comment]
Please review the changes in conf/application.conf.tmpl and adopt your local configuration accordingly. Since myself and @j0hj0h tripped over this, I am thinking about putting conf/application.conf back under version control with sensible defaults. What do you think, @philboeselager?

**Comment by philboeselager** [comment]
I am fine with putting conf/application.conf back under version control. "Sensible defaults": agree! I would prefer not to choose the default "elasticsearch" as a cluster name since that could cause clustering with other nodes in the same network (here in hbz). Default port 9300 seems fine.

**Comment by philboeselager** [comment]
Nevertheless there are some points bothering me:
- Raw types in LandingPage.java and Resource.java (I did not realize that before)
- We are currently collecting many errors and warning flags which indicates unclean code and should immideately stop that. I will email you a list so we can talk how to avoid it.
- Some nested for-loops --> could be replaced by method calls

**Comment by literarymachine** [comment]
`conf/application.conf` is back under version control: https://github.com/hbz/oerworldmap/commit/ea7470fd8dad06a8e5a611ac5d1f81d687bc1651. Left `es.cluster.name` to default to `elasticsearch`, updated README accordingly.

**Pull request merged**
