### PR TITLE
Replace "entity" by "entry" and "topic"

### LINKED ISSUE #950: Replace "entity"
There are some occurences of "entity" or "entities" left. For the sake of being better understandable, we should replace these, preferably with "entry/entries".

Occurrences:
- https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties
- https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties
- https://github.com/hbz/oerworldmap/blob/5b4b2a61e0f3448f5b85f1314ceaa8dab9696c6c/public/mustache/CountryIndex/read.mustache

### LINKED ISSUE #951: Don't differentiate between "Main Entity" and "Entities mentioned"
Currently, you can choose a main entity and and "entities mentioned". At the physical meeting we discussed that we can probably give up this distinction as it probably confuses users.

### PR DESCRIPTION
**Pull request by acka47**
Fixes #950, fixes #951 . I went for "main topic" instead of "main entity" and otherwise used  "entry".

### CODE REVIEW

**Comment by acka47** [comment]
Assigning this to @karindr for review of the wording. After this, @literarymachine can also take a look at it and finally deploy.

**Comment by literarymachine** [comment]
> Assigning this to @karindr for review of the wording.

Did you see that new Github "Reviewers" feature in the upper right? I just noticed it now...

**Comment by literarymachine** [comment]
> Did you see that new Github "Reviewers" feature in the upper right? I just noticed it now...

And now I understood that this is only for Pull Requests, so it won't play with our usual approach of re-assigning the issue for functional review.

**Comment by acka47** [comment]
I have read about the new reviewing functions but we don't use them yet. 

I didn't want to bring this up but as you are addressing this: Actually, we are now switching to the "review on pull request only" approach with lobid. It somehow made sense in the past but now it doesn't. As code review always comes after the functional review it the last one doing functional review just assigns the pull request to the other developer. This is basically the GitHub flow. (Also, people wopuldn't get it in our SWIB workshop which actually made us think about this again.)

**Comment by literarymachine** [comment]
> Actually, we are now switching to the "review on pull request only" approach with lobid.

I would very much suggest that we also do so here. Keeping things in line with lobid was the only reason we have been doing it as we have been doing, as I recall.

**Comment by acka47** [comment]
> I would very much suggest that we also do so here.

+1

**Comment by karindr** [comment]
> I went for "main topic" instead of "main entity" and otherwise used "entry".

Do I understand this right, you are referring to the fields below storries? If so I think it is a bit misleading because the main topic may be something that does not have an entry on the map. What about this:

Main entry mentioned:
Other entries mentioned:

**Comment by acka47** [comment]
You are right that "Main topic" is not an ideal solution. The problem I have with the term "main entry" is that it has a specific meaning in library science (see e.g. http://www.itsmarc.com/crs/mergedprojects/helpauth/helpauth/definition_main_entry.htm) and obviously also with regard to dictionaries, see http://www.dictionary.com/browse/main-entry.

"Main entry mentioned" is definitely better than only "Main entry" but I am not sure whether it might confuse people nonetheless.That said, I would be ok with following your proposal.

**Comment by karindr** [comment]
I think "Main entry mentioned" will be understood in this context.

Another possibility would be to delete "Main ..." and only use "Entries mentioned", most people will start with the main entry.

**Comment by acka47** [comment]
> I think "Main entry mentioned" will be understood in this context.

Ok. But what to do with the other direction, "Main topic of"?

> Another possibility would be to delete "Main ..." and only use "Entries mentioned", most people will start with the main entry.

We don't retain the order people have entered this in our data...

**Comment by acka47** [comment]
> what to do with the other direction, "Main topic of"?

Talking about this with @karindr and @trugwaldsaenger we agreed on the following solution:

1.) In the story template: Use "Main entry mentioned" in the story template.
2.) In the other templates: Use "Mentioned in" to list all stories the resource is mentioned in – whether as main entity or not.

The question is, how do I proceed to implement 2.)? I guess, this won't result in listing `mentionedIn` and `mainEntityOf` under one field labeled "Mentioned in", @literarymachine ?

```
Organization.mentionedIn = Mentioned in
Organization.mainEntityOf = Mentioned in
```

**Comment by literarymachine** [comment]
> The question is, how do I proceed to implement 2.)? I guess, this won't result in listing mentionedIn and mainEntityOf under one field labeled "Mentioned in", @literarymachine ?

No, this won't automatically do so. Nevertheless, it is not hard to implement. But putting that aside, if I recall correctly, we decided at our last team meeting to not differentiate between `mainEntityOf` and `mentionedIn` any longer?

**Comment by acka47** [comment]
You are correct, see #951 . We could have spared some time here. :-/

**Comment by acka47** [comment]
I removed the mainEntity stuff altogether from labels.properties and description properties. Is this sufficient to remove it from the editing template? If yes, this can be deployed and closed. Next step would be to migrate the data with SPARQL within #951.

**Comment by acka47** [comment]
As far as I can see, the PR should now cover everything to fix #950 and #951 . @literarymachine, please deploy on staging.

**Comment by literarymachine** [comment]
Deployed to beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:80240183-b976-4997-8637-b745538dcf09

**Comment by acka47** [comment]
+1

**Pull request merged**
