### PR TITLE
Add Collection type

### PR DESCRIPTION
**Pull request by literarymachine**
See #1939

### CODE REVIEW

**Comment by gandalfar** [comment]
This works great, thanks @literarymachine. I've tested it and added description and keywords field.

@dr0i please deploy to beta

**Review by gandalfar — APPROVED** [review]

**Comment by dr0i** [comment]
Deployed to beta.

**Comment by dr0i** [comment]
@gandalfar not sure why you assigned me. Shall I deploy to production?

**Comment by gandalfar** [comment]
@dr0i  Yes, please deploy to production. Sorry, I missed leaving a comment here.

**Comment by dr0i** [comment]
Deployed to production, closed.

**Comment by trugwaldsaenger** [comment]
Just checked again: Collections are not yet visible on production. @dr0i and @gandalfar, could you have a short look at this?

**Pull request merged**
