### PR TITLE
1079 find events by city and country

### PR DESCRIPTION
**Pull request by philboeselager**
Unintended hits should be reduced now.
I'm thinking about a way to search for country names, still.

### CODE REVIEW

**Comment by literarymachine** [comment]
@philboeselager something along the lines of 44fbf5d should make it possible to search for country names in different languages.

**Comment by philboeselager** [comment]
> Please configure https://github.com/hbz/oerworldmap/commit/60ca6be454e2b03586912e37c6b689e48d2e40fe in `scripts/fix_mapping.py`.

Done.

**Comment by philboeselager** [comment]
> @philboeselager something along the lines of https://github.com/hbz/oerworldmap/commit/44fbf5d682ed25ff0143f0c6e7da22a26703a56b should make it possible to search for country names in different languages.

I don't get your intention. Shall I implement something for it?

**Comment by literarymachine** [comment]
> Shall I implement something for it?

I haven't really tested this, just sketched it out. Could you implement a test case and check if it actually works this way?

**Pull request merged**
