### PR TITLE
Add Serlo story with picture and adjust folhas story.

### PR DESCRIPTION
**Pull request by acka47**
See #245,  #232 and #234.

### CODE REVIEW

**Comment by acka47** [comment]
I also added an image for the serlo story to /public/images but obviously this isn't included in this pull request. I don't know why...

**Comment by acka47** [comment]
I don't know what the procedure is for the review process, thus, I assigned this pull request and all four issues that are covered by it to @literarymachine. Does this correspond to the usual way we do it in this project?

**Comment by literarymachine** [comment]
For technical issues, definitely. For these preliminary content-issues I guess it is OK, too. Will ingest them to staging and then ping @trugwaldsaenger for review or something like that.

**Comment by trugwaldsaenger** [comment]
Sorry for being inconsistent at this point. On the one hand it seems to me that the affiliation to the service will be easier to understand intuitively. On the other hand I do not like to change rules too easily, because this might cause confusion, as we see now. I spoke with @acka47 and we deceided to keep the affiliation in this case to the service (serlo), but to wait for making it a general rule till we see more clearly!

**Pull request merged**
