### PR TITLE
1142 fix csv export delimiters in text

### PR DESCRIPTION
**Pull request by philboeselager**
- make AbstractCsvExporter be an interface
- unify fieldValuesToCsvString() of CsvDetailedExporter and CsvWithNestedIdsExporter in AbstractCsvExporter
- escape CSV export of strings by escaping all colons and embracing the whole string with colons
- add test case

### CODE REVIEW

**Comment by literarymachine** [comment]
+1

**Comment by literarymachine** [comment]
@philboeselager: one thing we might want to change is to export empty cells instead of `null` for fields without a value.

**Comment by literarymachine** [comment]
Another thing, but unrelated to this issue, is that currently not all fields are present in the export because of https://github.com/hbz/oerworldmap/blob/master/app/controllers/ResourceIndex.java#L88

**Comment by philboeselager** [comment]
> @philboeselager: one thing we might want to change is to export empty cells instead of null for fields without a value.

OK, I'm going to change it on this branch.

> Another thing, but unrelated to this issue, is that currently not all fields are present in the export because of https://github.com/hbz/oerworldmap/blob/master/app/controllers/ResourceIndex.java#L88

We could maybe introduce a selection option of fields to be exported?

**Pull request merged**
