### PR TITLE
256 import hewlett grant

### PR DESCRIPTION
**Pull request by philboeselager**

### CODE REVIEW

**Comment by literarymachine** [comment]
```
python import.py 'http://www.hewlett.org/grants/?search=hbz' hbz.json
page: 'http://www.hewlett.org/grants/page/1/?search=hbz'
North Rhine-Westphalian Library Service Center (hbz)
Traceback (most recent call last):
  File "import.py", line 485, in <module>
    main()
  File "import.py", line 478, in main
    imports = import_hewlett_data(sys.argv[1])
  File "import.py", line 449, in import_hewlett_data
    json = collect(link)
  File "import.py", line 373, in collect
    extract_address(address_clean)
  File "import.py", line 167, in extract_address
    address_line = extract_country(address_line)
  File "import.py", line 243, in extract_country
    address['schema:addressCountry'] = str(country.alpha_2)
AttributeError: 'Country' object has no attribute 'alpha_2'
```

**Comment by philboeselager** [comment]
The script contains a new import: [pycountry](https://pypi.python.org/pypi/pycountry). I assume that the installing of pycountry (pip install pycountry) is missing on the machine you've used.

Sorry, for not mentioning that. Should we document these requirements somewhere?

**Comment by literarymachine** [comment]
> I assume that the installing of pycountry (pip install pycountry) is missing on the machine you've used.

Thanks! It was not missing (which would have prevented the script from actually starting), but was outdated.

**Comment by literarymachine** [comment]
As @acka47 describes in https://github.com/hbz/oerworldmap/issues/256#issuecomment-259952237, we again need to restructure the output as exemplified [here](https://gist.github.com/acka47/29545e24a84dcac0fefa89bb6d47ebdc):

- Make the `Action` the top resource
- Remove the `@id` from `Grant`s, making them an "unidentified" type
- Remove namespace prefixes

Also, I would suggest to add a mapping of `granteeNumber` to `@id` in order to persist `Organization`s on repeated imports.

**Comment by philboeselager** [comment]
> Also, I would suggest to add a mapping of granteeNumber to @id in order to persist Organizations on repeated imports.

There is a such mapping. Data is stored in oerworldmap/id_map.json . We would have to adjust the UUIDs there. Is that what you were thinking about, @literarymachine ?

**Comment by literarymachine** [comment]
> Data is stored in oerworldmap/id_map.json

If I read this file correctly, I only see mappings for `hewlett_grant` and `hewlett_action` in there, both based on the URL of the grant. We don't need the one for the `Grant` any longer, since it now is "unidentified" and will always be re-imported with the surrounding `Action`. What I can't find is an ID map for the `Organization` which I would base on the `granteeNumber` instead of the URL (since, as we have seen, URLs might change). Ideally the ID for the `Grant` would also be based on an actual grant id, but it looks like that ID has been removed when Hewlett switched to the new site.

**Comment by philboeselager** [comment]
> If I read this file correctly, I only see mappings for hewlett_grant and hewlett_action in there, both based on the URL of the grant. We don't need the one for the Grant any longer, since it now is "unidentified" and will always be re-imported with the surrounding Action.

You will find the `hewlett_grant` entries because you've run the script before these entries were removed. Old file entries will not be removed once they are in the file. So for now, only `hewlett_action` entries are produced. If you want a "fresh" id_map, please remove the old one.

> What I can't find is an ID map for the Organization which I would base on the granteeNumber instead of the URL (since, as we have seen, URLs might change).

Done now. I've added the `@id` to the output as well. So we would have to replace these random UUIDs in both, the id_map.json and the output file, when adjusting data to feed it into the OER WorldMap. Of course, this is only necessary for one time per agent / organization. 

> Ideally the ID for the Grant would also be based on an actual grant id, but it looks like that ID has been removed when Hewlett switched to the new site.

Yes, the only "ID" that suits here is the URL part like 

    north-rhine-westphalian-library-service-center-hbz-for-the-development-of-an-oer-world-map-0

**Comment by literarymachine** [comment]
Other than two minor issues (see https://github.com/hbz/oerworldmap/pull/931/commits/47c3e51afefaa6e511f0318cb725566f43387ed2), this is good to go I think.

**Comment by philboeselager** [comment]
+1 Thanks for code review.

**Comment by literarymachine** [comment]
When testing the actual import of the Hewlett data into the system, I noticed some slight problems with the repetition of data. While this could be solved by modifying the import API, it would be simpler to change the data at this point. Could you perhaps refactor in a way where the `agent` of an Action is only fully described the first time it is encountered, and linked to in subsequent encounters?

I.e. the first time

```
  "agent": [{
    "location": {
      "@type": "Place", 
      "address": {
        "addressCountry": "DE", 
        "postalCode": "65067", 
        "@type": "PostalAddress", 
        "addressLocality": "Jülicher Straße 4, Köln"
      }
    }, 
    "@id": "urn:uuid:3e47be88-875a-42c0-a850-22b6e72a9992", 
    "@type": "Organization", 
    "name": {
      "@value": "North Rhine-Westphalian Library Service Center (hbz)", 
      "@language": "en"
    }
  }]
```
and subsequently
```
  "agent": [{
    "@id": "urn:uuid:3e47be88-875a-42c0-a850-22b6e72a9992"
  }]
```

**Comment by literarymachine** [comment]
Also, `agent`, `isFundedBy`, `name` and `description` should always be arrays.

**Comment by literarymachine** [comment]
> Could you perhaps refactor in a way where the agent of an Action is only fully described the first time it is encountered, and linked to in subsequent encounters?

Even simpler would probably to pull all identified resources into the top level array and always link when encountered as a property value.

**Comment by philboeselager** [comment]
> Even simpler would probably be to pull all identified resources into the top level array and always link when encountered as a property value. This would also make a whole of sense when ingesting the data with regards to validation against our schema!

Just to make sure I do get you right:

	[{
	  "name": [{}], 
	  "agent": [{
		"location": {}, 
		"@id": "<agentID>", 
		"@type": "", 
		"name": [{}]
	  }], 
	  "duration": "", 
	  "@context": "https://oerworldmap.org/assets/json/context.json", 
	  "@id": "<actionID>", 
	  "@type": "Action", 
	  "isFundedBy": [{
		"name": [{}], 
		"sameAs": "", 
		"hasAwardDate": "", 
		"hasMonetaryValue": "", 
		"duration": "", 
		"isAwardedBy": {"@id": "urn:uuid:0801e4d4-3c7e-11e5-9f0e-54ee7558c81f"}, 
		"@type": "Grant", 
		"description": [{}]
	  }]
	}]

becomes

	[{
	  "name": [{}], 
	  "agent": [{
		"@id": "<agentID>" 
	  }], 
	  "duration": "", 
	  "@context": "https://oerworldmap.org/assets/json/context.json", 
	  "@id": "<actionID>", 
	  "@type": "Action", 
	  "isFundedBy": [{
		"name": [{}], 
		"sameAs": "", 
		"hasAwardDate": "", 
		"hasMonetaryValue": "", 
		"duration": "", 
		"isAwardedBy": {"@id": "urn:uuid:0801e4d4-3c7e-11e5-9f0e-54ee7558c81f"}, 
		"@type": "Grant", 
		"description": [{}]
	  }]
	},
	{
		"location": {}, 
		"@id": "<agentID>", 
		"@type": "", 
		"name": [{}]
	}]

?

**Comment by literarymachine** [comment]
> Just to make sure I do get you right:

Exactly! Although I would place the extracted resources before they are referenced, i.e. at the beginning og the array.

**Comment by philboeselager** [comment]
> Also, agent, isFundedBy, name and description should always be arrays.

See https://github.com/hbz/oerworldmap/commit/9ffe5c21603ef403f88e18834e6663f9df5ab9d5

Extraction of agents: https://github.com/hbz/oerworldmap/commit/7bb3c751a4fb49e9c5c7518750e161eb8588a1ae Agents are stored in an updateable separate file: import/hewlett/agents.json. This means: you can keep the old agents.json and new agents will be added to it. In case you want to have all agents data updated, remove the old file. agents.json should be imported into the WorldMap before the grant data file.

**Comment by literarymachine** [comment]
+1, leaving this open until deployment which will probably take a couple of review iterations from @karindr et al.

**Comment by literarymachine** [comment]
@philboeselager I crawled using

     python import.py 'http://www.hewlett.org/grants/?search_program=31392' grants.json

today. Ingested to https://beta.oerworldmap.org/ but some entries are missing, e.g. [this one](http://www.hewlett.org/grants/north-rhine-westphalian-library-service-center-hbz-for-the-development-of-an-oer-world-map-0/).

**Comment by literarymachine** [comment]
@philboeselager also, some data seems to be imported twice, e.g. [this one](https://beta.oerworldmap.org/resource/urn:uuid:65c8df00-22de-4236-b41c-0676ed4953ae)

**Comment by acka47** [comment]
Discussing this with @literarymachine, we decided some last changes, especially to remove redundant information from a rpoject and the grant that funds it (see https://github.com/hbz/oerworldmap/issues/955#issuecomment-267963421):

- [ ] remove "name" from Grant 
- [ ] Create project `startTime` & `endTime` from `hasAwardDate` + duration; remove `hasAwardDate` & `duration`
- [ ] move "description" from Grant to Project
- [ ] Furthermore, we should remove the leading "For" in Project name

**Comment by philboeselager** [comment]
> @philboeselager I crawled using
>     python import.py 'http://www.hewlett.org/grants/?search_program=31392' grants.json
> today. Ingested to https://beta.oerworldmap.org/ but some entries are missing, e.g. this one.

Missing entries most probably result from non deterministic behaviour of the Hewlett search engine. This is nothing our crawler could have an influence on.

> also, some data seems to be imported twice, e.g. this one.

This is a follow-up of the issue assumed above. So far, the crawler does not expect non-deterministic search results, because it was not designed to do. The behaviour so far is:

- read Hewlett id
- lookup in id map
- take uuid from id map or generate new one
- put entry to import result

Up to now, there is no check, if the current import result does already contain this particular entry.

What we can do is

1. To catch doubles: 
    - avoid double entries in resulting json by checking for unexpected double results from crawled data
2. To catch missings:
    - compare number of resulting json entries to expected number of results reported on Hewlett site ("Viewing 1 - 10 of XXX Results")
    - while the number of resulting json entries is smaller than expected, crawl again (including search)
    - Optionally, to catch further eventual bugs and not run into an endless import, we can limit the number of repetitions to let's say 5.

Especially regarding 2., I am not sure, whether the benefit justifies the effort, because the same result can be obtained by repetitive searches / import script calls. Please decide, @literarymachine .

**Comment by literarymachine** [comment]
> To catch doubles:
avoid double entries in resulting json by checking for unexpected double results from crawled data

Yes, please.

**Comment by literarymachine** [comment]
> Especially regarding 2., I am not sure, whether the benefit justifies the effort, because the same result can be obtained by repetitive searches / import script calls. Please decide, @literarymachine .

If the doubles above are fixed, and you are sure that this is the problem, we might as well go with it.

**Comment by literarymachine** [comment]
> Missing entries most probably result from non deterministic behaviour of the Hewlett search engine. This is nothing our crawler could have an influence on.

http://www.hewlett.org/grants/?search_program=31392 has been giving me the same results for quite a while, at least "most probably".

**Comment by literarymachine** [comment]
Also, maybe it would make sense to store the crawled HTML somewhere, especially when it comes to debugging.

**Comment by philboeselager** [comment]
> http://www.hewlett.org/grants/?search_program=31392 has been giving me the same results for quite a while, at least "most probably".

There seems to be a temporary buffer or cache. I've observed, too, that results often are kept steady for a while. Please try later again.

**Comment by philboeselager** [comment]
> Also, maybe it would make sense to store the crawled HTML somewhere, especially when it comes to debugging.

Yes, that would be great. I've tried to find out how that would work best our case. Looks a bit like high costs as you have to store the files and also alter the links to point at these files.

If you know how to do it quite easily, could you please have a try?

**Comment by literarymachine** [comment]
> If you know how to do it quite easily, could you please have a try?

I have no ready solution, but I guess we could implement a generic get_url function that

- checks if there is a cached version
- if not, gets the URL and store a file with the some how encoded (base64?) URL as the filename
- if yes, returns the contents of that file

so that there would be no need to alter the links within the files in any way.

**Comment by literarymachine** [comment]
> I have no ready solution, but I guess we could implement a generic get_url

I'd probably put it here: https://github.com/hbz/oerworldmap/blob/256-importHewlettGrant/import/hewlett/import.py#L51

**Comment by philboeselager** [comment]
Honestly, I don't get that. You've to link from the results pages to the grants details pages, don't you?

**Comment by literarymachine** [comment]
> You've to link from the results pages to the grants details pages, don't you?

No, you just have to encapsulate fetching the pages, see dcea0f5. It might make sense to only cache the pages of individual grants and not the result lists, because the latter is likely to change but the former are not.

**Pull request merged**
