### PR TITLE
Replace availableChannel by url/inLanguage

### LINKED ISSUE #772: Languages of a service as extra point in the input template
As @trugwaldsaenger also mentioned, it would be clearer to have the languages of a service as extra point in the input template. At the moment the language is connected to the website. This may be misleading because a website for a repository for example can be in English but there could be resources in other languages in the repository. The person entering the data to the world map could misunderstand the template and only chose English instead of choosing the languages of all resources.

### PR DESCRIPTION
**Pull request by acka47**
Fixes #772 .

As preparation, I started with the code adjustments in the JSON schema and the editing template. I stopped before adjusting the Triple Store data as this we might run into problems adding data that doesn't conform to the schema. Or would such a patch simply be rejected, @literarymachine ? I slightly remember you said something like that but am not quite sure about it...

### CODE REVIEW

**Comment by literarymachine** [comment]
> Or would such a patch simply be rejected

No, the data migration currently bypasses validation against the JSON schema.

**Comment by literarymachine** [comment]
> I started with the code adjustments in the JSON schema and the editing template

Please note that `SchemaTest` is currently failing, you also need to adjust the test data.

**Comment by literarymachine** [comment]
#772 solved on the UI level, see https://github.com/hbz/oerworldmap/issues/772#issuecomment-248896844. Closing.

**Comment by acka47** [comment]
It's ok to close this for now. Generally, I think we will need to do some adjustments regarding the data model. I think we should reconsider this change then.

**Pull request closed without merging**
