### PR TITLE
Add funder to JSON schema and project web form.

### LINKED ISSUE #526: Add funder to project
We missed to include a `funder` property for type `Action`. To do:

- [x] Include in JSON schema
- [x] Add to Project form
- [x] [Edit] Add property labels 
- [x] [Edit] Adjust test files

### PR DESCRIPTION
**Pull request by acka47**
Fixes #526.

### CODE REVIEW

**Comment by literarymachine** [comment]
@acka47 Please update the test data.

**Comment by acka47** [comment]
> @acka47 Please update the test data.

I already did so, see https://github.com/hbz/oerworldmap/pull/536

**Comment by literarymachine** [comment]
> I already did so, see #536 

Ok, although I don't quite understand what this pull request is about then if #536 is already for `task/#526-AddFunder`.

**Comment by literarymachine** [comment]
Duplicate, see #536. Closing.

**Pull request closed without merging**
